serveur : main.cpp Modele/AbstractElement.cpp Modele/Client.cpp Modele/Fichier.cpp Modele/MyThread.cpp Modele/sock.cc Modele/sockdist.cc Controleur/BaseController.cpp Controleur/ThreadDownController.cpp Controleur/ThreadUpController.cpp
	g++ -pthread main.cpp Modele/AbstractElement.cpp Modele/Client.cpp Modele/Fichier.cpp Modele/MyThread.cpp Modele/sock.cc Modele/sockdist.cc Controleur/BaseController.cpp  Controleur/ThreadDownController.cpp Controleur/ThreadUpController.cpp -o serveur

